# Site settings
title:          Maneaba
description:    "cool"
url:            "https://maneaba.github.io"

# Author
author:
  name:         Maneaba
  url:          https://maneaba.github.io
  email:        maneaba@maneaba.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
